name = "UnallocatedArrays"
uuid = "43c9e47c-e622-40fb-bf18-a09fc8c466b6"
authors = ["ITensor developers <support@itensor.org> and contributors"]
version = "0.1.1"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
TypeParameterAccessors = "7e5a90cf-f82e-492e-a09b-e3e26432c138"
UnspecifiedTypes = "42b3faec-625b-4613-8ddc-352bf9672b8d"

[compat]
Adapt = "4.1.1"
FillArrays = "1.13.0"
TypeParameterAccessors = "0.2.1"
UnspecifiedTypes = "0.1.0"
julia = "1.10"
