[deps]
TypeParameterAccessors = "7e5a90cf-f82e-492e-a09b-e3e26432c138"
UnallocatedArrays = "43c9e47c-e622-40fb-bf18-a09fc8c466b6"
UnspecifiedTypes = "42b3faec-625b-4613-8ddc-352bf9672b8d"

[compat]
TypeParameterAccessors = "0.3.5"
UnallocatedArrays = "0.1.3"
UnspecifiedTypes = "0.1.3"
